### ISSUE TITLE
openstacksdk is required for this module

### ISSUE THREAD

**Issue by tehsmyers** [oasis-origin/oasis-pipeline#1]
In an openstack scenario using this library, I'm seeing the following task from a molecule create playbook fail:

```
    TASK [Create security group] ***************************************************
    fatal: [localhost]: FAILED! => {"changed": false, "msg": "openstacksdk is required for this module"}
```

In the logs, it's abundantly clear that `openstacksdk` is being installed, leading me to think that this task is potentially being run outside the virtualenv. I'm not sure at this point if this is a problem with oasis-pipeline, but that's where my investigation is starting.

Right now, I think that for whatever reason, it might be that the create task is running outside the virtualenv and causing this issue, but I'm unable to reproduce this locally to start debugging.

**Comment by tehsmyers** [comment]
Okay, this is actually blocking me now, so...

I logged into the Jankies box as the jenkins user, activated the venv, and saw the same error when running molecule. If you hop into that venv's python shell and import `openstack`, you see the actual nested error:
```
>>> import openstack
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  <...>
  File "/path/to/rhsm/.venv/lib/python2.7/site-packages/dogpile/cache/region.py", line 15, in <module>
    from decorator import decorate
ImportError: cannot import name decorate
```

The `decorate` function is relatively new to the `decorator` module, and openstacksdk properly declares dependencies that would require a suitable version of `decorator` to be installed, but there is a copy of it installed system-wide, leading me to think that venvs created by the pipeline need to be fixed to stop using system site-packages.

**Comment by tehsmyers** [comment]
Ah, I see it now: `Requirement already satisfied: decorator>=3.4.0 in /usr/lib/python2.7/site-packages (from openstacksdk>=0.15.0->shade) (3.4.0)`

```
Python 2.7.5 (default, Feb 20 2018, 09:19:12) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import decorator
>>> decorator.__version__
'3.4.0'
>>> from decorator import decorate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name decorate
>>> decorator.__file__
'/usr/lib/python2.7/site-packages/decorator.pyc'
```

I was transposing stuff. I thought openstack sdk was requiring `decorator>=4.3`

https://github.com/openstack/openstacksdk/blob/master/requirements.txt#L14

The `decorator.decorate` function, as far as I can tell, is over 3 years old, and was introduced at or about version 4.0.0: https://github.com/micheles/decorator/commit/cf20ab367249c9eca473d6f9989f0721e451b033

`openstacksdk` needs its requirements updated, and in the meantime I can just throw a workaround in here.

**Comment by tehsmyers** [comment]
Here's the full traceback, which basically says "it's not openstacksdk's fault"

```
>>> import openstack                                                                                                                                                                                                                           
Traceback (most recent call last):                                                                                                                                                                                                             
  File "<stdin>", line 1, in <module>                                                                                                                                                                                                          
  File ".venv/lib/python2.7/site-packages/openstack/__init__.py", line 17, in <module>                                                                                                        
    import openstack.connection                                                                                                                                                                                                                
  File ".venv/lib/python2.7/site-packages/openstack/connection.py", line 166, in <module>                                                                                                     
    from openstack.cloud import openstackcloud as _cloud                                                                                                                                                                                       
  File ".venv/lib/python2.7/site-packages/openstack/cloud/openstackcloud.py", line 35, in <module>                                                                                            
    import dogpile.cache                                                                                                                                                                                            
  File ".venv/lib/python2.7/site-packages/dogpile/cache/__init__.py", line 1, in <module>                                                              
    from .region import CacheRegion, register_backend, make_region  # noqa                                                                                                                             
  File ".venv/lib/python2.7/site-packages/dogpile/cache/region.py", line 15, in <module>                                                                                                      
    from decorator import decorate                                                                                                                                                                                                             
ImportError: cannot import name decorate                 
```

It's the import of `dogpile.cache` that breaks stuff, and the actual breaking import happens in `dogpile.cache.region`. I suspect that if https://github.com/sqlalchemy/dogpile.cache/blob/master/setup.py#L61 was updated to be version-restricted to `>=4` or they changed their use of the decorator api to not use `decorator.decorate`, everything would be fine. I'll follow up on this later.

**Comment by xiaojueguan** [comment]
try pip install decorator===4.4.0
and this works for me
